Problem Statement:
Creating a fake profile and email account is much easy for the spammers, they pretend like a genuine person in their spam emails, these spammers target those peoples who are not aware about these frauds. So, it is needed to Identify those spam mails which are fraud, In this project will identify those spam by using techniques of machine learning and NLP



Analytical Tools:
 Naive Bayes and nltk


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
df=pd.read_csv('/content/spam.csv',encoding='latin-1')#upoload dataset we use encoding(parameter) because we have many latin words.

In [ ]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [ ]:
df.rename(columns={"v1":"class_label","v2":"Message"},inplace=True)##re-namaing the column name as class_label and Message

In [ ]:
df

class_label                                            Message  \
0            ham  Go until jurong point, crazy.. Available only ...   
1            ham                      Ok lar... Joking wif u oni...   
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3            ham  U dun say so early hor... U c already then say...   
4            ham  Nah I don't think he goes to usf, he lives aro...   
...          ...                                                ...   
5567        spam  This is the 2nd time we have tried 2 contact u...   
5568         ham              Will Ì_ b going to esplanade fr home?   
5569         ham  Pity, * was in mood for that. So...any other s...   
5570         ham  The guy did some bitching but I acted like i'd...   
5571         ham                         Rofl. Its true to its name   

     Unnamed: 2 Unnamed: 3 Unnamed: 4  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
5567        NaN        NaN        NaN  
5568        NaN        NaN        NaN  
5569        NaN        NaN        NaN  
5570        NaN        NaN        NaN  
5571        NaN        NaN        NaN  

[5572 rows x 5 columns]

In [ ]:
df.shape

(5572, 5)

In [ ]:
df.columns

Index(['class_label', 'Message', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [ ]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1,inplace=True)#dropping unwanted columns inplace=True because it change in original dataset

In [ ]:
df

class_label                                            Message
0            ham  Go until jurong point, crazy.. Available only ...
1            ham                      Ok lar... Joking wif u oni...
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...
3            ham  U dun say so early hor... U c already then say...
4            ham  Nah I don't think he goes to usf, he lives aro...
...          ...                                                ...
5567        spam  This is the 2nd time we have tried 2 contact u...
5568         ham              Will Ì_ b going to esplanade fr home?
5569         ham  Pity, * was in mood for that. So...any other s...
5570         ham  The guy did some bitching but I acted like i'd...
5571         ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
##to see how much messages are there as ham and spam classes
df.class_label.value_counts()

ham     4825
spam     747
Name: class_label, dtype: int64

In [ ]:
#we are going to change the string into numeric
df["class_label"]=df["class_label"].apply(lambda x:1 if x=='spam' else 0)## if spam give 1 else 0 ### the apply function iterate over evler single element in panda series

In [ ]:
df

class_label                                            Message
0               0  Go until jurong point, crazy.. Available only ...
1               0                      Ok lar... Joking wif u oni...
2               1  Free entry in 2 a wkly comp to win FA Cup fina...
3               0  U dun say so early hor... U c already then say...
4               0  Nah I don't think he goes to usf, he lives aro...
...           ...                                                ...
5567            1  This is the 2nd time we have tried 2 contact u...
5568            0              Will Ì_ b going to esplanade fr home?
5569            0  Pity, * was in mood for that. So...any other s...
5570            0  The guy did some bitching but I acted like i'd...
5571            0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
# split into train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
                                            df['Message'],
                                            df["class_label"],
                                            test_size=0.3,#training data is 70% and testing is 30%
                                            random_state=0)

In [ ]:
#see how many ham and spam msg in training data
y_train.value_counts()

0    3391
1     509
Name: class_label, dtype: int64

In [ ]:
#see how many ham and spam msg in test data
y_test.value_counts()

0    1434
1     238
Name: class_label, dtype: int64

In [ ]:
##COUNTER VECTORIZER(used to convert the words into numbers)
#convert a collection of text documents to a matrix of token counts. using bow /bad of words
vectorizer=CountVectorizer(
                         lowercase=True, # convert to lowercase before tokenizing change them initi lower case bec if we have same word two time but in uppder and lower case then it give 2 vectot so to avoid that we have changed
                         stop_words='english'  # remove stop words (eg: and it does not help in classifiying if it is ham or spam so remove)
                         )

In [ ]:
x_train_transformed = vectorizer.fit_transform(x_train)  # give vector for x_train
x_test_transformed = vectorizer.transform(x_test) # give vector for x_test

In [ ]:
x_train_transformed ##3900rows and 6840 columns its a matrix its sparse matrix because it contain many zero

<3900x6839 sparse matrix of type '<class 'numpy.int64'>'
	with 30363 stored elements in Compressed Sparse Row format>

In [ ]:
x_train_transformed.toarray()# to see the matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectorizer.get_feature_names_out()

array(['00', '000', '000pes', ..., 'ûïharry', 'ûò', 'ûówell'],
      dtype=object)

In [ ]:
#MODEL TRAINING
classifier=MultinomialNB()
classifier.fit(x_train_transformed,y_train)

MultinomialNB()

In [ ]:
ytest_predicted_lables=classifier.predict(x_test_transformed)##TO test if the model has trained well be pass the test data set and vectors

In [ ]:
ytest_predicted_lables# predicted class lables for the x_test emails 0 ham 1 spam

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_test.count()

1672

In [ ]:
y_test# actual lable in test dataset
ytest_predicted_lables# predicted lables for test dataset

array([0, 0, 0, ..., 0, 0, 0])

testing model performance

In [ ]:
print("ACCURACY SCORE:",accuracy_score(y_test,ytest_predicted_lables))#test and predicted

ACCURACY SCORE: 0.9850478468899522


In [ ]:
result =confusion_matrix(y_test,ytest_predicted_lables)#1423-TP 11-FP 224-TN 14-FN
print(result)

[[1423   11]
 [  14  224]]


In [ ]:
##testing unknown email
new_email="Please call you have won a prize of 1000000 dollers"

In [ ]:
new_email_transformed=(vectorizer.transform([new_email]))# CO VE CONVERT INTO NUMBER USING COUNT VECTORIZER AND PASS THE MSG

In [ ]:
new_email_transformed

<1x6839 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [ ]:
new_email_transformed.toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [ ]:
classifier.predict(new_email_transformed)# CLASS LABLE as output

array([1])

In [ ]:
#########################################################3

In [ ]:
ham_new_mail="Good morning students"
ham_new_mail_transformed=(vectorizer.transform([ham_new_mail]))

In [ ]:
ham_new_mail_transformed

<1x6839 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [ ]:
ham_new_mail_transformed.toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [ ]:
classifier.predict(ham_new_mail_transformed)

array([0])

Conclusion:
Detection of spam is important for securing message and e-mail communication. The accurate detection of spam is a big issue, and many detection methods have been proposed by various researchers. However, these methods have a lack of capability to detect the spam accurately and efficiently, we use machine learning and deep learning method in this project and have correctly classify the spam email.
